/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 16 21:12:15 GMT 2022
 */

package org.apache.commons.lang3.WillEvoSuite;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang3.compare.ObjectToStringComparator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ObjectToStringComparator_ESTest extends ObjectToStringComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ObjectToStringComparator objectToStringComparator0 = new ObjectToStringComparator();
      Object object0 = new Object();
      int int0 = objectToStringComparator0.compare(object0, (Object) null);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ObjectToStringComparator objectToStringComparator0 = new ObjectToStringComparator();
      int int0 = objectToStringComparator0.compare((Object) null, objectToStringComparator0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ObjectToStringComparator objectToStringComparator0 = new ObjectToStringComparator();
      int int0 = objectToStringComparator0.compare((Object) null, (Object) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ObjectToStringComparator objectToStringComparator0 = new ObjectToStringComparator();
      Object object0 = new Object();
      int int0 = objectToStringComparator0.compare("!q", object0);
      assertEquals(4, int0);
  }
}
